name: Dylan White
favicon: null
layout_spectrum: 0.51769
typography_spectrum: 0.93471
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101010'
    - '#7f735d'
    - '#a9997c'
    - '#615847'
    - '#dbc9a4'
  brandStrength: 0.9703524631913751
  lightness: 0.37655401858501136
  saturation: 0.8067754399962723
  rhythmicContrast: 0.0797165057156235
purpose: []
